# Generated by Django 5.0.4 on 2024-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("SNo", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=14)),
                ("content", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
